// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/2/2025, 10:39:49 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/dieterlorenzo/psicologakarem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/plugins/**/*.{js,ts,mjs}","/Users/dieterlorenzo/psicologakarem/composables/**/*.{js,ts,mjs}","/Users/dieterlorenzo/psicologakarem/utils/**/*.{js,ts,mjs}","/Users/dieterlorenzo/psicologakarem/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;