// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/7/2025, 6:34:45 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/dieterlorenzo/terapli/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/terapli/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/terapli/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/terapli/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/terapli/plugins/**/*.{js,ts,mjs}","/Users/dieterlorenzo/terapli/composables/**/*.{js,ts,mjs}","/Users/dieterlorenzo/terapli/utils/**/*.{js,ts,mjs}","/Users/dieterlorenzo/terapli/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/terapli/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/terapli/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/terapli/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;