// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/26/2025, 10:33:45 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/dieterlorenzo/psicologakarem/psicokarem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/psicokarem/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/psicokarem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/psicokarem/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/psicokarem/plugins/**/*.{js,ts,mjs}","/Users/dieterlorenzo/psicologakarem/psicokarem/composables/**/*.{js,ts,mjs}","/Users/dieterlorenzo/psicologakarem/psicokarem/utils/**/*.{js,ts,mjs}","/Users/dieterlorenzo/psicologakarem/psicokarem/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/psicokarem/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/psicokarem/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dieterlorenzo/psicologakarem/psicokarem/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;