-- Crear tabla para registros emocionales avanzados
create table if not exists public.emociones_avanzadas (
  id bigint generated by default as identity primary key,
  paciente_id uuid references auth.users(id) on delete cascade not null,
  fecha timestamptz default now() not null,
  estado_general text check (estado_general in ('muy bien', 'bien', 'neutral', 'mal', 'muy mal')) not null,
  emociones text[] default '{}',
  influencias text[] default '{}',
  reflexion text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Crear índices para mejorar el rendimiento
create index if not exists emociones_avanzadas_paciente_id_idx on public.emociones_avanzadas(paciente_id);
create index if not exists emociones_avanzadas_fecha_idx on public.emociones_avanzadas(fecha desc);

-- Habilitar RLS (Row Level Security)
alter table public.emociones_avanzadas enable row level security;

-- Política: Los pacientes solo pueden ver sus propios registros
create policy "Los pacientes pueden ver sus propios registros emocionales"
  on public.emociones_avanzadas
  for select
  using (auth.uid() = paciente_id);

-- Política: Los pacientes pueden insertar sus propios registros
create policy "Los pacientes pueden insertar sus propios registros emocionales"
  on public.emociones_avanzadas
  for insert
  with check (auth.uid() = paciente_id);

-- Política: Los pacientes pueden actualizar sus propios registros
create policy "Los pacientes pueden actualizar sus propios registros emocionales"
  on public.emociones_avanzadas
  for update
  using (auth.uid() = paciente_id)
  with check (auth.uid() = paciente_id);

-- Política: Los pacientes pueden eliminar sus propios registros
create policy "Los pacientes pueden eliminar sus propios registros emocionales"
  on public.emociones_avanzadas
  for delete
  using (auth.uid() = paciente_id);

-- Función para actualizar updated_at automáticamente
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger para actualizar updated_at
create trigger update_emociones_avanzadas_updated_at
  before update on public.emociones_avanzadas
  for each row
  execute function public.handle_updated_at();

-- Comentarios para documentación
comment on table public.emociones_avanzadas is 'Registros diarios del estado emocional de los pacientes';
comment on column public.emociones_avanzadas.estado_general is 'Estado emocional general del día';
comment on column public.emociones_avanzadas.emociones is 'Array de hasta 3 emociones específicas';
comment on column public.emociones_avanzadas.influencias is 'Array de factores que influyeron en el estado de ánimo';
comment on column public.emociones_avanzadas.reflexion is 'Reflexión personal opcional del paciente';
