
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AlertaBono: typeof import("../components/AlertaBono.vue")['default']
export const BonosPaciente: typeof import("../components/BonosPaciente.vue")['default']
export const Card: typeof import("../components/Card.vue")['default']
export const CardRecurso: typeof import("../components/CardRecurso.vue")['default']
export const CookieConsent: typeof import("../components/CookieConsent.vue")['default']
export const EmotionalTransition: typeof import("../components/EmotionalTransition.vue")['default']
export const EmptyState: typeof import("../components/EmptyState.vue")['default']
export const EvolucionEmocional: typeof import("../components/EvolucionEmocional.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const GreetingModal: typeof import("../components/GreetingModal.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const HistorialSesiones: typeof import("../components/HistorialSesiones.vue")['default']
export const InactivityModal: typeof import("../components/InactivityModal.vue")['default']
export const InstallPWAButton: typeof import("../components/InstallPWAButton.vue")['default']
export const InstallPWAModal: typeof import("../components/InstallPWAModal.vue")['default']
export const InversionSection: typeof import("../components/InversionSection.vue")['default']
export const LoadingSpinner: typeof import("../components/LoadingSpinner.vue")['default']
export const MensajeCard: typeof import("../components/MensajeCard.vue")['default']
export const MensajeInput: typeof import("../components/MensajeInput.vue")['default']
export const ModalCompartirRecurso: typeof import("../components/ModalCompartirRecurso.vue")['default']
export const ModalEnviarRecurso: typeof import("../components/ModalEnviarRecurso.vue")['default']
export const ModalNuevaCita: typeof import("../components/ModalNuevaCita.vue")['default']
export const ModalNuevoBloqueo: typeof import("../components/ModalNuevoBloqueo.vue")['default']
export const ModalNuevoPaciente: typeof import("../components/ModalNuevoPaciente.vue")['default']
export const ModalNuevoRecurso: typeof import("../components/ModalNuevoRecurso.vue")['default']
export const ModalRecurso: typeof import("../components/ModalRecurso.vue")['default']
export const NotasPrivadas: typeof import("../components/NotasPrivadas.vue")['default']
export const NotificacionesBell: typeof import("../components/NotificacionesBell.vue")['default']
export const PWAInstallWrapper: typeof import("../components/PWAInstallWrapper.vue")['default']
export const PacienteCard: typeof import("../components/PacienteCard.vue")['default']
export const PacienteEvolucion: typeof import("../components/PacienteEvolucion.vue")['default']
export const PanelEmocionalAvanzado: typeof import("../components/PanelEmocionalAvanzado.vue")['default']
export const ProgressBar: typeof import("../components/ProgressBar.vue")['default']
export const RecursoCard: typeof import("../components/RecursoCard.vue")['default']
export const ResumenCard: typeof import("../components/ResumenCard.vue")['default']
export const SesionCard: typeof import("../components/SesionCard.vue")['default']
export const TablaSesiones: typeof import("../components/TablaSesiones.vue")['default']
export const VisualizacionEmocional: typeof import("../components/VisualizacionEmocional.vue")['default']
export const CoordinacionDashboardCard: typeof import("../components/coordinacion/DashboardCard.vue")['default']
export const DashboardDailyQuote: typeof import("../components/dashboard/DailyQuote.vue")['default']
export const DashboardCard: typeof import("../components/dashboard/DashboardCard.vue")['default']
export const DashboardEmotionChart: typeof import("../components/dashboard/EmotionChart.vue")['default']
export const DashboardEmotionTracker: typeof import("../components/dashboard/EmotionTracker.vue")['default']
export const DashboardEmotionalInsight: typeof import("../components/dashboard/EmotionalInsight.vue")['default']
export const DashboardHeaderGreeting: typeof import("../components/dashboard/HeaderGreeting.vue")['default']
export const DashboardNextSessionCard: typeof import("../components/dashboard/NextSessionCard.vue")['default']
export const DashboardResourceGrid: typeof import("../components/dashboard/ResourceGrid.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCCached: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAlertaBono: LazyComponent<typeof import("../components/AlertaBono.vue")['default']>
export const LazyBonosPaciente: LazyComponent<typeof import("../components/BonosPaciente.vue")['default']>
export const LazyCard: LazyComponent<typeof import("../components/Card.vue")['default']>
export const LazyCardRecurso: LazyComponent<typeof import("../components/CardRecurso.vue")['default']>
export const LazyCookieConsent: LazyComponent<typeof import("../components/CookieConsent.vue")['default']>
export const LazyEmotionalTransition: LazyComponent<typeof import("../components/EmotionalTransition.vue")['default']>
export const LazyEmptyState: LazyComponent<typeof import("../components/EmptyState.vue")['default']>
export const LazyEvolucionEmocional: LazyComponent<typeof import("../components/EvolucionEmocional.vue")['default']>
export const LazyFooter: LazyComponent<typeof import("../components/Footer.vue")['default']>
export const LazyGreetingModal: LazyComponent<typeof import("../components/GreetingModal.vue")['default']>
export const LazyHeader: LazyComponent<typeof import("../components/Header.vue")['default']>
export const LazyHistorialSesiones: LazyComponent<typeof import("../components/HistorialSesiones.vue")['default']>
export const LazyInactivityModal: LazyComponent<typeof import("../components/InactivityModal.vue")['default']>
export const LazyInstallPWAButton: LazyComponent<typeof import("../components/InstallPWAButton.vue")['default']>
export const LazyInstallPWAModal: LazyComponent<typeof import("../components/InstallPWAModal.vue")['default']>
export const LazyInversionSection: LazyComponent<typeof import("../components/InversionSection.vue")['default']>
export const LazyLoadingSpinner: LazyComponent<typeof import("../components/LoadingSpinner.vue")['default']>
export const LazyMensajeCard: LazyComponent<typeof import("../components/MensajeCard.vue")['default']>
export const LazyMensajeInput: LazyComponent<typeof import("../components/MensajeInput.vue")['default']>
export const LazyModalCompartirRecurso: LazyComponent<typeof import("../components/ModalCompartirRecurso.vue")['default']>
export const LazyModalEnviarRecurso: LazyComponent<typeof import("../components/ModalEnviarRecurso.vue")['default']>
export const LazyModalNuevaCita: LazyComponent<typeof import("../components/ModalNuevaCita.vue")['default']>
export const LazyModalNuevoBloqueo: LazyComponent<typeof import("../components/ModalNuevoBloqueo.vue")['default']>
export const LazyModalNuevoPaciente: LazyComponent<typeof import("../components/ModalNuevoPaciente.vue")['default']>
export const LazyModalNuevoRecurso: LazyComponent<typeof import("../components/ModalNuevoRecurso.vue")['default']>
export const LazyModalRecurso: LazyComponent<typeof import("../components/ModalRecurso.vue")['default']>
export const LazyNotasPrivadas: LazyComponent<typeof import("../components/NotasPrivadas.vue")['default']>
export const LazyNotificacionesBell: LazyComponent<typeof import("../components/NotificacionesBell.vue")['default']>
export const LazyPWAInstallWrapper: LazyComponent<typeof import("../components/PWAInstallWrapper.vue")['default']>
export const LazyPacienteCard: LazyComponent<typeof import("../components/PacienteCard.vue")['default']>
export const LazyPacienteEvolucion: LazyComponent<typeof import("../components/PacienteEvolucion.vue")['default']>
export const LazyPanelEmocionalAvanzado: LazyComponent<typeof import("../components/PanelEmocionalAvanzado.vue")['default']>
export const LazyProgressBar: LazyComponent<typeof import("../components/ProgressBar.vue")['default']>
export const LazyRecursoCard: LazyComponent<typeof import("../components/RecursoCard.vue")['default']>
export const LazyResumenCard: LazyComponent<typeof import("../components/ResumenCard.vue")['default']>
export const LazySesionCard: LazyComponent<typeof import("../components/SesionCard.vue")['default']>
export const LazyTablaSesiones: LazyComponent<typeof import("../components/TablaSesiones.vue")['default']>
export const LazyVisualizacionEmocional: LazyComponent<typeof import("../components/VisualizacionEmocional.vue")['default']>
export const LazyCoordinacionDashboardCard: LazyComponent<typeof import("../components/coordinacion/DashboardCard.vue")['default']>
export const LazyDashboardDailyQuote: LazyComponent<typeof import("../components/dashboard/DailyQuote.vue")['default']>
export const LazyDashboardCard: LazyComponent<typeof import("../components/dashboard/DashboardCard.vue")['default']>
export const LazyDashboardEmotionChart: LazyComponent<typeof import("../components/dashboard/EmotionChart.vue")['default']>
export const LazyDashboardEmotionTracker: LazyComponent<typeof import("../components/dashboard/EmotionTracker.vue")['default']>
export const LazyDashboardEmotionalInsight: LazyComponent<typeof import("../components/dashboard/EmotionalInsight.vue")['default']>
export const LazyDashboardHeaderGreeting: LazyComponent<typeof import("../components/dashboard/HeaderGreeting.vue")['default']>
export const LazyDashboardNextSessionCard: LazyComponent<typeof import("../components/dashboard/NextSessionCard.vue")['default']>
export const LazyDashboardResourceGrid: LazyComponent<typeof import("../components/dashboard/ResourceGrid.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyContentRenderer: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
export const LazyMDC: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
export const LazyMDCCached: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
export const LazyMDCRenderer: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
export const LazyMDCSlot: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
export const LazyVitePwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaAssets: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
export const LazyPwaAppleImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage")['default']>
export const LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage")['default']>
export const LazyPwaFaviconImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage")['default']>
export const LazyPwaMaskableImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage")['default']>
export const LazyPwaTransparentImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
